version: '2'
services:
    jenkins-data:
        build: 
            context: ./jenkins-data
        volumes:
        - /c/Users/jenkins:/var/jenkins_home
        container_name: jenkins-data

    jenkins-app:
        build: 
            context: ./jenkins-app
        depends_on:
        - jenkins-data
        volumes_from:
        - jenkins-data
        ports:
        - "50000:50000"
        - "8080:8080"
        container_name: jenkins-app

    bitbucket:
        build:
            context: ./local-bitbucket
        volumes:
        - /c/Users/bitbucket:/var/atlassian/application-data/bitbucket
        ports:
        - "7990:7990"
        - "7999:7999"
        container_name: bitbucket

    artifactory-registry:
        image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-registry:latest
        volumes:
        - /c/Users/artifactory:/artifactory
        ports:
        - "8081:8081"
        - "443:443"
        - "80:80"
        container_name: artifactory-registry