version: '2'
services:
    jenkins-data:
        build: 
            context: ./jenkins-data
        volumes:
        - /docker-workspaces/jenkins:/var/jenkins_home
        container_name: jenkins-data

    jenkins-app:
        build: 
            context: ./jenkins-app
        depends_on:
        - jenkins-data
        volumes_from:
        - jenkins-data
        ports:
        - "50000:50000"
        - "8080:8080"
        container_name: jenkins-app
        extra_hosts:
        - "docker-virtual.art.local docker-dev-local2.art.local docker-prod-local2.art.local:192.168.99.100"

    bitbucket:
        build:
            context: ./local-bitbucket
        volumes:
        - /docker-workspaces/bitbucket:/var/atlassian/application-data/bitbucket
        ports:
        - "7990:7990"
        - "7999:7999"
        container_name: bitbucket

    artifactory-registry:
        image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-registry:latest
        volumes:
        - /docker-workspaces/artifactory:/artifactory
        ports:
        - "8081:8081"
        - "443:443"
        - "80:80"
        container_name: artifactory

    basic-image-builder:
        build:
            context: ./basic-image-builder
        ports:
        - "2222:22"
        container_name: basic-image-builder
        privileged: true
        extra_hosts:
        - "docker-virtual.art.local docker-dev-local2.art.local docker-prod-local2.art.local:192.168.99.100"
